// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3f-iVUa34gi94yMHwCAHNw_WHS7mDU3o',
    appId: '1:1039228391142:web:7fb72d1c744c8a7d6b3527',
    messagingSenderId: '1039228391142',
    projectId: 'test-cli-56',
    authDomain: 'test-cli-56.firebaseapp.com',
    storageBucket: 'test-cli-56.appspot.com',
    measurementId: 'G-9N33LBL4D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVyLXIup-qL3BvhVdGgXW1X5265LW48LQ',
    appId: '1:1039228391142:android:2dc9226f8122ed3f6b3527',
    messagingSenderId: '1039228391142',
    projectId: 'test-cli-56',
    storageBucket: 'test-cli-56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATBxUGNYNxe3HDMg8sBlVj3Q_8BNx2Iok',
    appId: '1:1039228391142:ios:d1aad0b0690f47766b3527',
    messagingSenderId: '1039228391142',
    projectId: 'test-cli-56',
    storageBucket: 'test-cli-56.appspot.com',
    iosBundleId: 'com.example.demoFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATBxUGNYNxe3HDMg8sBlVj3Q_8BNx2Iok',
    appId: '1:1039228391142:ios:d1aad0b0690f47766b3527',
    messagingSenderId: '1039228391142',
    projectId: 'test-cli-56',
    storageBucket: 'test-cli-56.appspot.com',
    iosBundleId: 'com.example.demoFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3f-iVUa34gi94yMHwCAHNw_WHS7mDU3o',
    appId: '1:1039228391142:web:867c511ec531d1ce6b3527',
    messagingSenderId: '1039228391142',
    projectId: 'test-cli-56',
    authDomain: 'test-cli-56.firebaseapp.com',
    storageBucket: 'test-cli-56.appspot.com',
    measurementId: 'G-7JF7Y2YVC0',
  );
}
